"""empty message

Revision ID: 4929cf4fc45e
Revises: 3aae19114c0f
Create Date: 2024-01-28 01:42:47.278149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4929cf4fc45e'
down_revision = '3aae19114c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_categories')
    # ### end Alembic commands ###
